---
title: "Intro to R Markdown"
author: "K. D. Erickson"
date: "5/17/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Topic Ideas

Note: Send out email ahead of workshop about packages to download? 

Test w/ Adam: Display mode? 

I have created public GitHub repository for this workshop. Briefly show how to download from a GitHub repository 

- Output formats: Word, HTML, PDF  (notebook, presentations, Shiny documents and presentations )
- What is the difference between R Notebook, R Markdown, R script? 
- Basics: 
  - How to create a Markdown file? 
  - What is a code chunk?
  - How to knit a markdown file? 
  - How to set working directory in markdown? 
  - How to insert images
  - How to make tables
    -kable package
  -
- Useful tips and tricks for figure output (and other output options) such as: 
  -Controlling figure height
  - Adding table of contents (Useful for long scripts)
  - When to use cache
  - the equivalent of mpar(mfrow=c(x,y))
  - Suppressing warnings/messages
  - Hiding code chunks
- When NOT to use markdown
- When is Markdown useful? 
  - Showing collaborators
  - Creating vignettes for R packages
  - Showing large plots that you can scroll through 
  - Keeping well-documented code (Why did you code things the way you did?)
  - Teaching (demo how can run code snippets. No more typos, missing parentheses!)
  - Easy to share in-progress results with coauthors who may not be familiar with R
  - A place to store all of those exploratory plots you make along the way, so you can look at them later without having to rerun the whole analysis. 
  -Writing supplemental information
  -Preparing something for your website
  -Emailing colleagues

- Using Markdown to create presentations
- Bookdown
- Extras if time: 
  - Making tables in Markdown
  - How to embed picture in Markdown
  - Adding citations to Markdown 
    -link to BibTex resource
  - How to write equations in Markdown
    -link to LaTeX primer 
  - Things to watch out for in pdf and word: words going off into margins 
